language: python
python: "2.7"
branches:
    only:
        - master
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
addons:
    firefox: "28.0"
install:
    - "pip install -r test_requirements.txt"
    - "pip install -r requirements.txt"
    - "pip install -r doc_requirements.txt"
    - "sudo ./scripts/install_browsermob_proxy.sh"
script:
    - "pylint bok_choy"
    - "./run_tests.sh"
